Updates project version based on GitHub release
expressots/expresso-site-doc pull request #16
Opened 2023-08-19 02:33 UTC by juliano-soares

The provided code fetches the latest version from GitHub and updates the currentVersion variable in the docusaurus.config.js file. This step is already implemented in your code.

2023-08-19 06:50 UTC, rsaz requested changes

2023-08-19 06:50 UTC, rsaz commented on docusaurus.config.js
You need to check how are you going to get the version from a promise to the `currentVersion` variable in the line 8

2023-08-21 23:09 UTC, Amorim33 commented on package.json
> +    "axios": "^1.4.0",
Should not `package-lock` change too?

2023-10-09 03:46 UTC, rsaz commented
Completed on PR #37 . Thanks @juliano-soares

2023-10-09 03:46 UTC, closed without merging